# ========== FONT ==========
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0

# Enable ligatures
enable_ligatures always


# ========== CURSOR ==========
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
cursor_text_color #101418
cursor #42a5f5


# ========== WINDOW PADDING ==========
window_padding_width 14
window_padding_height 12


# ========== BACKGROUND / FOREGROUND ==========
background #101418
foreground #e0e2e8

selection_background #0d47a1
selection_foreground #e0e2e8


# ========== COLOR PALETTE ==========
color0  #101418
color1  #e64c49
color2  #72d66e
color3  #dbd07b
color4  #4186c9
color5  #c87b7f
color6  #42a5f5
color7  #abb2bf
color8  #5c6370
color9  #e05f61
color10 #89e086
color11 #e8de97
color12 #9ad9ff
color13 #3a829e
color14 #5a7aab
color15 #ffffff


# ========== SCROLL ==========
scrollback_lines 5000
wheel_scroll_multiplier 3.0


# ========== WINDOW BEHAVIOR ==========
confirm_os_window_close 0
remember_window_size  yes
initial_window_width  900
initial_window_height 600


# ========== WAYLAND FIXES ==========
linux_display_server wayland


# ========== PERFORMANCE ==========
repaint_delay 10
input_delay 3

# ===== Ghostty-like mouse behavior =====

# Left click drag = select text
mouse_map left click ungrabbed select

# Auto copy on select (like Ghostty)
copy_on_select yes

# Right click = paste
mouse_map right click ungrabbed paste_from_clipboard
